name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login ghcr.io -u REALalphas -p ${{ secrets.CR_PAT }}
        docker build . --file Dockerfile --tag label-it:latest
        docker push ghcr.io/realalphas/label-it:latest
